### ISSUE TITLE
An error occured with new Matlab version

### ISSUE THREAD

**Issue by silencer1127** [robertoostenveld/cifti-matlab#10]
Hi,

When I was trying to read cifti file with Matlab R2016b in a Linux system, I got the following error message which pointed to a problem inside the binary file:

> Invalid MEX-file
'.../cifti/private/ft_getopt.mexa64':
'.../cifti/private/ft_getopt.mexa64:
undefined symbol: mxErrMsgTxt.
Error in ft_read_cifti (line 59)
readdata         = ft_getopt(varargin, 'readdata', []);   % the default depends on
file size, see below 

However, it worked fine with my old Matlab R2015a. Could you please help check it out and fix it if possible? 

Thanks,
Andrew

**Comment by robertoostenveld** [comment]
Hi Andrew,

thanks for reporting. R2016b has not yet arrived on our linux machines, so I cannot reproduce it at the moment. 

Could you try running the following test script
https://github.com/fieldtrip/fieldtrip/blob/master/test/test_ft_getopt.m

Could you perhaps also check that you have the latest version of the ft_getopt mex file? I have not had any of the FieldTrip users mentioning problems, although I would expect that some (outside Nijmegen) FT users will be using 206b on linux as well. 

These are the ones I have (on my mac), and these are all consistent. 

```mac011> find ~/matlab/cifti -name  ft_getopt.mexa64 -exec md5sum {} \;
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/cifti/private/ft_getopt.mexa64

mac011> find ~/matlab/fieldtrip -name  ft_getopt.mexa64 -exec md5sum {} \;
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/connectivity/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/engine/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/fileio/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/forward/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/inverse/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/peer/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/plotting/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/qsub/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/specest/private/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/src/ft_getopt.mexa64
734baa372bebe4e99f9b76dcaa7a3574  /Users/roboos/matlab/fieldtrip/utilities/ft_getopt.mexa64
```

**Comment by silencer1127** [comment]
Sorry for the late reply. The files I have were outdated and I have tested the newest version on R2016b, they worked fine. Thank you for your help!

Best,
Andrew
