### ISSUE TITLE
Problems reading a dconn.nii (33gb)

### ISSUE THREAD

**Issue by Dazzid** [robertoostenveld/cifti-matlab#2]
Hi,

I'm writing because after trying to read a nii file (838KB) with this line command 
mycifti = ft_read_cifti('Conte69.MyelinAndCorrThickness.32k_fs_LR.dtseries.nii');

I get an error related to a precompiled MEX:
"Invalid MEX-file '/Users/David/Dave_Matlab/cifti-matlab-master/private/ft_getopt.mexmaci64':
dlopen(/Users/David/Dave_Matlab/cifti-matlab-master/private/ft_getopt.mexmaci64, 6): Symbol not
found: _mxErrMsgTxt
  Referenced from: /Users/David/Dave_Matlab/cifti-matlab-master/private/ft_getopt.mexmaci64
  Expected in: /Applications/MATLAB_R2015b.app/bin/maci64/libmx.dylib

Error in ft_read_cifti (line 60)
readdata         = ft_getopt(varargin, 'readdata', false);   % the default depends on file size,
see below"

I'm using Matlab R2015b (8.6.0.267246) 64-bit (maci64) 
I'm programming an app for Specs lab in Pompeu Fabra University. http://www.brainx3.com
And the goal is to build a connectome using HCP data, but I'm having a lot of problems reading those -nii files.
How can I make the cifti-matlab pass this error?
Thanks for the help
David

**Comment by robertoostenveld** [comment]
Hi David,

The mex files don't work (yet) on MATLAB R2015b. If you have an older version of MATLAB, please use that. If not, please download ft_getopt.c from https://github.com/fieldtrip/fieldtrip/tree/master/src and recompile the mex file.

best
Robert

**Comment by Dazzid** [comment]
Hi Robert,
Thanks a lot for your answer. I will compile recompile the mex.
Best

David

**Comment by Dazzid** [comment]
Hi Robert,
One more question, after compile mex and also xml_findstr.mexmaci64. Now I
have a strange error:
The problem appears in Xparse_count: 0, but if it is changed to 1 in
xml_parser.m, it works until it arrives to 5 and then has a problem with
'contents'
Xparse_count: 1
Xparse_count: 2
Xparse_count: 3
Xparse_count: 4
Xparse_count: 5
Reference to non-existent field 'contents'.

The complete error is the following:
Cell contents indices must be greater than 0

Error in xml_parser>tag_element (line 228)
        xtree{Xparse_count} = element;

Error in xml_parser>compile (line 199)
                            frag = tag_element(frag);

Error in xml_parser (line 134)
tree = compile(tree);

Error in xmltree (line 41)
                tree.tree = xml_parser(varargin{1});

Error in ft_read_cifti (line 153)
tree = xmltree(xmldata);

It it familiar to you? I have the same error with almost all .nii files I'm
trying from HCP.
Best

David

**Comment by Dazzid** [comment]
sorry, I forgot to mention how I'm reading the file:

mycifti = ft_read_cifti(...


'/Users/David/Desktop/HumanConnectomeProject/HCP_S500_R468_rfMRI_MIGP_d4500ROW_zcorr/HCP_S500_R468_MIGPd4500ROW.dconn.nii',
...

    'readdata', false);

**Comment by robertoostenveld** [comment]
Hi David,

I think that the xmltree code (originally from spm) that I am using has issues on R2015b. I just updated the code to the latest version of xmltree. Could you try once more?

Robert

**Comment by Dazzid** [comment]
Hi Robert,
I still have errors. I'm using the HCP_S500 file that is 33GB.
the error is:

Error using ft_getopt
the first input should contain key-value pairs

Error in ft_read_cifti (line 59)
readdata         = ft_getopt(varargin, 'readdata', []);   % the default depends on file size, see below

Error in init (line 3)
mycifti =
ft_read_cifti('//Users/David/Desktop/HumanConnectomeProject/HCP_S500_R468_rfMRI_MIGP_d4500ROW_zcorr/HCP_S500_R468_MIGPd4500ROW.dconn.nii',
'readdata');

No idea what is causing the error.
Should I try with other machine and matlab version?
Thanks for the help
David

**Comment by Dazzid** [comment]
OK! Riccardo from the lab has found my mistake, with your new version it is working well now. 
Thanks for the support :)

**Comment by Sheljohn** [comment]
This is quite old, but if anyone else has an issue running older versions of FieldTrip in newer versions of Matlab, the following should fix them:

 - Change directory to fieldtrip, delete all Mex files in the `src/` directory
 - Edit `src/ft_getopt.c` and replace any `mxErrMsgTxt` to `mexErrMsgTxt` (notice the 'mex' instead of 'mx')
 - Rename `mxSerialize.c` to `mxSerialize.cpp` (same for `mxDeserialize`)
 - Edit those files, and replace the prototype declarations to:
```
// MX_API_VER has unfortunately not changed between R2013b and R2014a,
// so we use the new MATRIX_DLL_EXPORT_SYM as an ugly hack instead
#if defined(__cplusplus) && defined(MATRIX_DLL_EXPORT_SYM)
    namespace matrix{ namespace detail{ namespace noninlined{ namespace mx_array_api{
#endif
 
EXTERN_C mxArray* mxSerialize(mxArray const *);
EXTERN_C mxArray* mxDeserialize(const void *, size_t);
// and so on, for any other MEX C functions that migrated to C++ in R2014a
 
#if defined(__cplusplus) && defined(MATRIX_DLL_EXPORT_SYM)
    }}}}
    using namespace matrix::detail::noninlined::mx_array_api;
#endif
```
_(source: http://undocumentedmatlab.com/blog/serializing-deserializing-matlab-data)_
 - run `ft_compile_mex.m`, you might get warnings/errors in text, but the script
 - then replace all Mex files in FieldTrip with the newly compiled ones:
```
[~,mex_files] = system(['find . -type f -name "*.' mexext '"']);
not_src = cellfun( @isempty, strfind(mex_files,'src/') );
to_replace = mex_files(not_src);
src_files = mex_files(~not_src);

for i = 1:numel(to_replace)
    [p,n,e] = fileparts(to_replace{i}); 
    [~,k]=ismember(n,src_files_names); 
    if k > 0
        disp([ fullfile(p,[n e]) ' will be replaced by ' src_files{k} ]); 
        copyfile(src_files{k},fullfile(p,[n e])); 
    end
end
```

**Comment by robertoostenveld** [comment]
Hi @Sheljohn 

The mxErrMsgTxt -> mexErrMsgTxt and the handling of both c and cpp for mxSerialize have already been resolved in the master FieldTrip branch some time ago. See also http://bugzilla.fcdonders.nl/show_bug.cgi?id=2452 and http://github.com/fieldtrip/fieldtrip.

I have just updated the cifti-matlab package to include all latest versions from FieldTrip.

best
Robert
